name: Package Publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Pack
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          dotnet pack src/BuMa.Gambling/BuMa.Gambling.csproj -c Release -o ./nupkg
      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
